### ISSUE TITLE
Macbook m1 can not run program?

### ISSUE THREAD

**Issue by DavidKotykOfficial** [Doriandarko/o1-engineer#12]
whenever my computer tries to run o1 engineer i keep getting

Error while communicating with OpenAI: Completions.create() got an unexpected keyword argument 'max_completion_tokens'
ERROR:root:Error while communicating with OpenAI: Completions.create() got an unexpected keyword argument 'max_completion_tokens'
Failed to generate a planning response. Please try again.
ERROR:root:AI failed to generate a planning response.

I have an m1 macbook.

**Comment by whrit** [comment]
Also have the same issue and on an M3 MBP- Thinking this might be OAI tier related and having access to the o1 API. Believe I'm a Tier 3 account, so in theory should have access to o1 and o1 Mini... I'll run a test on my Windows machine to see if it's the same there.

**Comment by whrit** [comment]
> Also have the same issue and on an M3 MBP- Thinking this might be OAI tier related and having access to the o1 API. Believe I'm a Tier 3 account, so in theory should have access to o1 and o1 Mini... I'll run a test on my Windows machine to see if it's the same there.

Yeah confirming this is an API Tier issue. Running on Windows gave me the error that I don't have access to the model. Quite strange given I should be Tier 3 and have access to o1..

**Comment by Doriandarko** [comment]
You need to update your OpenAI python package

_________________________
*Pietro Schirano*
Founder | EverArt <http://everart.ai>

**Comment by DavidKotykOfficial** [comment]
> update your OpenAI python package

Worked, Thank you!!!

**Comment by kalebzaki4** [comment]
It looks like you're encountering an error related to the `Completions.create()` function in OpenAI's API while trying to run the `o1 engineer` program on your M1 MacBook. The specific issue is that the function is being called with an unexpected keyword argument `max_completion_tokens`, which is likely not valid or supported.

Here are a few steps to troubleshoot and resolve the issue:

### 1. **Check OpenAI API Version:**
   - The `max_completion_tokens` argument might be outdated or not supported in the version of the OpenAI API you are using. Make sure that you are using the latest version of the OpenAI Python package. You can update it by running:
     ```bash
     pip install --upgrade openai
     ```
   After updating, review the official OpenAI API documentation to ensure you’re using the correct parameters for your API calls.

### 2. **Correct API Call:**
   - The correct argument might be `max_tokens` instead of `max_completion_tokens`. You could try replacing `max_completion_tokens` with `max_tokens` in the code where the API call is made. For example:
     ```python
     response = openai.Completion.create(
         engine="text-davinci-003",
         prompt="Your prompt here",
         max_tokens=100  # Replace with the desired value
     )
     ```

### 3. **Compatibility with M1 MacBook:**
   - The issue does not seem to be specific to your M1 MacBook, but it’s always a good idea to check that all dependencies are properly installed and compatible with your architecture. If you're using virtual environments (e.g., `venv` or `conda`), make sure they are correctly set up for the M1 chip.

### 4. **Review Logs and Documentation:**
   - Check if there’s an issue tracker or documentation specific to the `o1 engineer` project that references this issue. It’s possible others have faced the same problem, and there may already be a fix or patch.

If none of these steps resolve the issue, you might want to report this to the project maintainers, including details about your setup (Python version, OpenAI library version, etc.) to help them investigate further.
